/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mac.gltf --transform
Author: MANUGR (https://sketchfab.com/MANUGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mac-laptop-8018f263bfe14dd68584cbff81a68a23
Title: MAC LAPTOP
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/mac-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["portatil_Material_#27_0"].geometry}
        material={materials.Material_27}
        position={[-24.58, 85.65, 78.07]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.33, 0.23, 0.23]}
      />
      <mesh
        geometry={nodes["Box001_Material_#28_0"].geometry}
        material={materials.Material_28}
        position={[-24.55, 85.87, 81.58]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[0.61, 0.41, 0.27]}
      />
    </group>
  );
}

useGLTF.preload("/mac-transformed.glb");
