/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mars.gltf --transform
Author: Whystler (https://sketchfab.com/Whystler)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/mars-poster-fe37ea9b8bdd4debab6605facd087bc4
Title: Mars Poster
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/mars-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_frame}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_poster}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_matting}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mars-transformed.glb");
